// 'use client'

import "./globals.css";
import Nav from "./nav";

export const metadata = {
  title: "store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className=" h-screen   bg-gradient-to-br from-gray-400-400 via-gray-100 to-gray-50">
        <Nav />

        {children}
      </body>
    </html>
  );
}
